import json
import os
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.request import Request, urlopen

ENGINE_URL = os.getenv("ENGINE_URL", "https://binance-30s-engine.onrender.com").rstrip("/")

HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dragon Resurrection — Control</title>
<style>
:root{--bg:#07080c;--panel:#10131a;--line:#252b36;--text:#f2f5fa;--muted:#8993a3;--good:#35dc8a;--bad:#ff6170;--gold:#d8a94b;--blue:#63adff;--warn:#ffbd5c}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 78% -15%,#382914 0,#101017 25%,#07080c 58%);color:var(--text);font:14px Inter,system-ui,sans-serif}.wrap{max-width:1450px;margin:auto;padding:14px}.top{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:12px}.brand{font-size:24px;font-weight:900}.brand span{color:var(--gold)}.sub,.mini,.footer{color:var(--muted);font-size:11px}.actions{display:flex;gap:7px;flex-wrap:wrap}.btn,.select{background:#0d1118;color:var(--text);border:1px solid var(--line);border-radius:9px;padding:9px 11px}.btn{cursor:pointer}.pill{border:1px solid #31513f;background:#0d2118;color:#73e8ac;border-radius:999px;padding:9px 12px;font-weight:800;font-size:11px}.pill.live{border-color:#70403f;background:#26100f;color:#ff8b8f}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.grid3{display:grid;grid-template-columns:1.25fr .9fr .9fr;gap:9px;margin-top:9px}.card{background:linear-gradient(180deg,#141923,#0e1118);border:1px solid var(--line);border-radius:14px;padding:14px;box-shadow:0 10px 30px #0005}.label{font-size:10px;text-transform:uppercase;letter-spacing:.09em;color:var(--muted)}.value{font-size:24px;font-weight:900;margin-top:5px}.delta{font-size:11px;margin-top:3px}.good{color:var(--good)}.bad{color:var(--bad)}.warn{color:var(--warn)}.section{font-weight:850;margin-bottom:9px}.row{display:flex;justify-content:space-between;align-items:center;gap:8px}.status{display:grid;grid-template-columns:1fr 1fr;gap:7px}.statusItem{background:#0a0e14;border:1px solid var(--line);padding:9px;border-radius:9px}.dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--good);margin-right:5px}.dot.off{background:var(--bad)}.meter{height:7px;background:#1b222d;border-radius:8px;overflow:hidden;margin-top:10px}.fill{height:100%;width:0;background:linear-gradient(90deg,var(--gold),var(--good))}.tabs{display:flex;gap:6px;margin:9px 0}.tab{padding:8px 11px;border-radius:8px;border:1px solid var(--line);color:var(--muted);cursor:pointer;background:#0d1118}.tab.active{color:var(--text);border-color:#6b5429;background:#1a160e}.hidden{display:none}table{width:100%;border-collapse:collapse;min-width:850px}th,td{padding:8px;border-bottom:1px solid var(--line);text-align:left;font-size:11px}th{color:var(--muted);font-size:9px;text-transform:uppercase;position:sticky;top:0;background:#141923}.tableWrap{overflow:auto;max-height:410px}.tag{display:inline-flex;border:1px solid #334052;border-radius:6px;padding:3px 6px;background:#0b1017}.reject{color:var(--warn)}.err{color:var(--bad)}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}.grid3{grid-template-columns:1fr 1fr}}@media(max-width:600px){.grid,.grid3{grid-template-columns:1fr}.top{align-items:flex-start}.brand{font-size:20px}}
</style></head><body><div class="wrap">
<div class="top"><div><div class="brand">🐉 <span>DRAGON RESURRECTION</span></div><div class="sub">Arbitrage command center · Spot + Futures + Triangular · live telemetry + qualification diagnostics</div></div><div class="actions"><button class="btn" id="pause">Pause updates</button><button class="btn" id="reset">Reset view</button><span class="pill" id="modePill">● CHECKING</span></div></div>
<div class="grid"><div class="card"><div class="label">Equity</div><div class="value" id="equity">$0.000000</div><div class="delta good" id="pnl">+$0.000000</div></div><div class="card"><div class="label">Compounded return</div><div class="value" id="ret">0.0000%</div><div class="delta" id="dd">Drawdown 0.00%</div></div><div class="card"><div class="label">Qualified opportunities</div><div class="value" id="opps">0</div><div class="delta" id="split">Spot 0 · Futures 0</div></div><div class="card"><div class="label">Rejected / near-miss</div><div class="value" id="near">0</div><div class="delta" id="topReject">—</div></div></div>
<div class="grid3"><div class="card"><div class="section">Best qualified opportunities</div><div class="label">Spot triangular</div><div class="value" id="bestSpot">No qualified setup</div><div class="delta" id="spotMeta">—</div><div class="meter"><div class="fill" id="spotFill"></div></div><div class="label" style="margin-top:14px">Futures basis / triangular</div><div class="value" id="bestFut">No qualified setup</div><div class="delta" id="futMeta">—</div></div><div class="card"><div class="section">Connection health</div><div class="status"><div class="statusItem"><span class="dot" id="sd"></span>Spot WS <b id="sw">0/0</b></div><div class="statusItem"><span class="dot" id="fd"></span>Futures WS <b id="fw">0/0</b></div><div class="statusItem">Spot updates <b id="su">0</b></div><div class="statusItem">Futures updates <b id="fu">0</b></div></div><div class="footer" id="health">Connecting…</div></div><div class="card"><div class="section">Qualification model</div><div class="status"><div class="statusItem">Min net <b id="minNet">—</b></div><div class="statusItem">Max net <b id="maxNet">—</b></div><div class="statusItem">Tri cost <b id="triCost">—</b></div><div class="statusItem">Basis cost <b id="basisCost">—</b></div><div class="statusItem">Stale limit <b id="stale">—</b></div><div class="statusItem">Diagnostics <b id="diagScans">0</b></div></div></div></div>
<div class="tabs"><button class="tab active" data-tab="oppsTab">Opportunities</button><button class="tab" data-tab="diagTab">Diagnostics</button><button class="tab" data-tab="systemTab">System</button></div>
<div id="oppsTab" class="card"><div class="row"><div class="section">Live opportunity tape</div><select id="filter" class="select"><option value="ALL">All engines</option><option value="SPOT_TRIANGULAR">Spot triangular</option><option value="SPOT_FUTURES_BASIS">Spot/Futures basis</option><option value="FUTURES_TRIANGULAR">Futures triangular</option></select></div><div class="tableWrap"><table><thead><tr><th>Engine</th><th>Market / Path</th><th>Direction</th><th>Gross</th><th>Fees</th><th>Slippage</th><th>Net</th><th>Notional</th></tr></thead><tbody id="rows"><tr><td colspan="8">Waiting for telemetry…</td></tr></tbody></table></div></div>
<div id="diagTab" class="card hidden"><div class="section">Why opportunities are rejected</div><div class="tableWrap"><table><thead><tr><th>Engine</th><th>Symbol / Path</th><th>Gross</th><th>Net</th><th>Rejection reason</th></tr></thead><tbody id="diagRows"><tr><td colspan="5">Waiting for diagnostics…</td></tr></tbody></table></div></div>
<div id="systemTab" class="card hidden"><div class="grid3" style="margin-top:0"><div><div class="section">Runtime</div><div id="runtime">—</div><div class="footer" id="err">Errors: 0</div></div><div><div class="section">Execution safety</div><div class="statusItem">Mode <b id="modeText">CHECKING</b></div><div class="statusItem" style="margin-top:7px">Live execution <b id="liveText">CHECKING</b></div><div class="statusItem" style="margin-top:7px">Supported <b id="supported">—</b></div><div class="statusItem" style="margin-top:7px">Circuit <b id="circuit">—</b></div></div><div><div class="section">Recent errors</div><div id="errorList" class="mini">No errors reported.</div></div></div></div>
<div class="footer" style="margin-top:8px">Refresh: 1 second. Diagnostics never bypass the execution safety gate. Live orders remain fail-closed.</div></div>
<script>
const $=id=>document.getElementById(id), money=x=>'$'+Number(x||0).toFixed(6), num=(x,d=2)=>Number(x||0).toFixed(d);let paused=false,latest=null;
function setText(id,v){$(id).textContent=v}
function esc(x){return String(x??'—').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]))}
function renderRows(d){const f=$('filter').value,rows=(d.top_opportunities||[]).filter(x=>f==='ALL'||x.engine===f).slice(0,80);$('rows').innerHTML=rows.map(x=>{const z=x.diagnostic||{};return '<tr><td><span class="tag">'+esc(x.engine)+'</span></td><td>'+esc(x.path||x.symbol)+'</td><td>'+esc(x.direction||'—')+'</td><td>'+num(x.gross_bps)+' bps</td><td>'+num(z.fees_bps)+' bps</td><td>'+num(z.slippage_bps)+' bps</td><td class="good">'+num(x.net_bps)+' bps</td><td>'+money(x.notional_usdt)+'</td></tr>'}).join('')||'<tr><td colspan="8">No qualified opportunities — open Diagnostics to see why.</td></tr>'}
function renderDiag(d){const rows=(d.near_misses||[]).slice().reverse().slice(0,100);$('diagRows').innerHTML=rows.map(x=>'<tr><td><span class="tag">'+esc(x.engine)+'</span></td><td>'+esc(x.path||x.symbol)+'</td><td>'+num(x.gross_bps)+' bps</td><td>'+num(x.net_bps)+' bps</td><td class="reject">'+esc(x.reason)+'</td></tr>').join('')||'<tr><td colspan="5">No rejected candidates recorded yet.</td></tr>';const counts=d.rejection_counts||{};const top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];setText('near',rows.length);setText('topReject',top?top[0]+' · '+top[1]+' rejects':'No rejections yet')}
function render(d){latest=d;const live=!!d.live_execution;setText('equity',money(d.equity));setText('pnl',(Number(d.paper_pnl||0)>=0?'+':'')+money(d.paper_pnl));setText('ret',num(d.compound_return_pct,4)+'%');setText('dd','Drawdown '+num(d.drawdown_pct,2)+'%');setText('opps',(d.spot_opportunities||0)+(d.futures_opportunities||0));setText('split','Spot '+(d.spot_opportunities||0)+' · Futures '+(d.futures_opportunities||0));setText('sw',(d.spot_sockets_up||0)+'/'+(d.spot_sockets||0));setText('fw',(d.futures_sockets_up||0)+'/'+(d.futures_sockets||0));setText('su',d.quote_updates_spot||0);setText('fu',d.quote_updates_futures||0);$('sd').className='dot '+(d.ws_spot?'':'off');$('fd').className='dot '+(d.ws_futures?'':'off');setText('health',(d.ws_spot?'Spot connected':'Spot reconnecting')+' · '+(d.ws_futures?'Futures connected':'Futures reconnecting')+' · errors '+(d.errors||0));const s=d.best_spot,f=d.best_futures;setText('bestSpot',s?((s.path||s.symbol)+' · '+num(s.net_bps)+' bps'):'No qualified setup');setText('spotMeta',s?'Gross '+num(s.gross_bps)+' bps · '+money(s.notional_usdt):'The scanner is running; inspect Diagnostics for near-misses.');$('spotFill').style.width=Math.min(100,Math.max(0,(s?s.net_bps:0)*4))+'%';setText('bestFut',f?(f.path||f.symbol)+' · '+num(f.net_bps)+' bps':'No qualified setup');setText('futMeta',f?(f.direction||'')+' · gross '+num(f.gross_bps)+' bps':'Basis/triangular candidates are shown in Diagnostics when rejected.');const m=d.diagnostic_model||{};setText('minNet',num(m.min_net_bps)+' bps');setText('maxNet',num(m.max_net_bps)+' bps');setText('triCost',num(m.triangular_cost_bps)+' bps');setText('basisCost',num(m.basis_cost_bps)+' bps');setText('stale',num(m.stale_ms,0)+' ms');setText('diagScans',d.diagnostic_scans||0);setText('runtime',(d.halted?'HALTED':'RUNNING')+' · '+num(d.uptime_seconds,0)+'s · '+num(d.scans,0)+' scans');setText('err','Errors: '+(d.errors||0)+(d.last_error?' · '+d.last_error:''));setText('supported',d.live_supported_engine||'—');const cb=d.live_circuit_breaker||{};setText('circuit',cb.halted?'HALTED':'READY');setText('modeText',live?'LIVE':'PAPER');setText('liveText',live?'ON':'OFF');$('liveText').className=live?'good':'bad';$('modeText').className=live?'good':'bad';const pill=$('modePill');pill.textContent=live?'● LIVE TRADING · SPOT TRIANGLE':'● PAPER MODE';pill.className='pill '+(live?'live':'');renderRows(d);renderDiag(d);const es=(d.error_log||[]).slice().reverse().slice(0,8);$('errorList').innerHTML=es.length?es.map(e=>'<div class="err">'+new Date((e.ts||0)*1000).toLocaleTimeString()+' · '+esc(e.message)+'</div>').join(''):'No errors reported.'}
async function refresh(){if(paused)return;try{const r=await fetch('/api/stats?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);render(await r.json())}catch(e){setText('health','Dashboard connection error: '+e.message)}}
$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Resume updates':'Pause updates'};$('reset').onclick=()=>{latest=null;setText('near','0');setText('topReject','View reset')};$('filter').onchange=()=>{if(latest)renderRows(latest)};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));['oppsTab','diagTab','systemTab'].forEach(x=>$(x).classList.add('hidden'));b.classList.add('active');$(b.dataset.tab).classList.remove('hidden')});refresh();setInterval(refresh,1000);
</script></body></html>'''

class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path.startswith('/api/stats'):
            try:
                req=Request(ENGINE_URL+'/stats.json',headers={'User-Agent':'Dragon-Resurrection-Dashboard/2.0'})
                with urlopen(req,timeout=5) as r: body=r.read()
                self.send_response(200);self.send_header('Content-Type','application/json');self.send_header('Cache-Control','no-store');self.end_headers();self.wfile.write(body)
            except Exception as e:
                body=json.dumps({'error':str(e)}).encode();self.send_response(502);self.send_header('Content-Type','application/json');self.send_header('Cache-Control','no-store');self.end_headers();self.wfile.write(body)
            return
        body=HTML.encode();self.send_response(200);self.send_header('Content-Type','text/html; charset=utf-8');self.send_header('Cache-Control','no-store');self.send_header('Content-Length',str(len(body)));self.end_headers();self.wfile.write(body)
    def log_message(self,*args): pass

if __name__=='__main__':
    port=int(os.getenv('PORT','10000'));ThreadingHTTPServer(('0.0.0.0',port),Handler).serve_forever()
